### ISSUE TITLE
varnishlogbeat stopped

### ISSUE THREAD

**Issue by kfkawalec** [phenomenes/varnishlogbeat#1]
Alter some time service was crashed.
```
Sep 14 09:21:01 cdn5 systemd[1]: Stopped varnishlogbeat.
Sep 14 09:21:01 cdn5 systemd[1]: Started varnishlogbeat.
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: panic: runtime error: index out of range
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: goroutine 1 [running]:
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: panic(0x8df300, 0xc420010090)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/beater.(*Varnishlogbeat).harvest.func1(0xc400ea0494, 0xc4203c2590, 0x9, 0x9783ed, 0x6, 0xc4203c25a0, 0x10, 0x0)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/beater/varnishlogbeat.go:93 +0xac8
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/vendor/github.com/phenomenes/vago.dispatchCallback(0x7f99f0000c90, 0x7f99ef7fdce0, 0x7f99f0000e40, 0xc4201afa70)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/vendor/github.com/phenomenes/vago/log.go:143 +0x36d
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/vendor/github.com/phenomenes/vago._cgoexpwrap_a4ca2347e13f_dispatchCallback(0x7f99f0000c90, 0x7f99ef7fdce0, 0x7f99f0000e40, 0x3
ef7fdcc0)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011??:0 +0x3f
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/vendor/github.com/phenomenes/vago._Cfunc_VSLQ_Dispatch(0x7f99f0000f70, 0x85a8a0, 0x7f99f0000e40, 0x0)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011??:0 +0x4d
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/vendor/github.com/phenomenes/vago.(*Varnish).Log(0xc4201bd180, 0x0, 0x0, 0x2, 0x3, 0xc4202e02e0, 0x0, 0x0)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/vendor/github.com/phenomenes/vago/log.go:78 +0x4a0
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/beater.(*Varnishlogbeat).harvest(0xc4202e0220, 0xe21f20, 0xc4201bd1c0)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/beater/varnishlogbeat.go:124 +0x14a
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/beater.(*Varnishlogbeat).Run(0xc4202e0220, 0xc42019a000, 0xc42019a0a8, 0xb)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/beater/varnishlogbeat.go:54 +0xee
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/vendor/github.com/elastic/beats/libbeat/beat.(*Beat).launch(0xc42019a000, 0x9bfe18, 0x0, 0x0)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:225 +0x6df
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: github.com/phenomenes/varnishlogbeat/vendor/github.com/elastic/beats/libbeat/beat.Run(0x97ec73, 0xe, 0x0, 0x0, 0x9bfe18, 0x51bade, 0xc4200001a0)
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/vendor/github.com/elastic/beats/libbeat/beat/beat.go:141 +0x65
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: main.main()
Sep 14 09:21:01 cdn5 varnishlogbeat[1015]: #011/root/go/src/github.com/phenomenes/varnishlogbeat/main.go:12 +0x54
Sep 14 09:21:01 cdn5 systemd[1]: varnishlogbeat.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 14 09:21:01 cdn5 systemd[1]: varnishlogbeat.service: Unit entered failed state.
Sep 14 09:21:01 cdn5 systemd[1]: varnishlogbeat.service: Failed with result 'exit-code'.
Sep 14 09:21:01 cdn5 systemd[1]: varnishlogbeat.service: Service hold-off time over, scheduling restart.
Sep 14 09:21:01 cdn5 systemd[1]: Stopped varnishlogbeat.
```

**Comment by phenomenes** [comment]
@kfkawalec sorry for the slow response. Are you still having this problem?
If so, could you please let me know what os and versions of varnish, elk and go are you running?

**Comment by kfkawalec** [comment]
Yes, i have still this problem.
Ubuntu 16, Varnish 4.
Elasticsearch 5, but problem is in reading data from Varnish not sending to EL.

**Comment by phenomenes** [comment]
varnish 4.0, 4.1? and what go version?
Also how did you install varnishlogbeat?

**Comment by kfkawalec** [comment]
Varnish 4.1.8
I build from sourcecode.

**Comment by phenomenes** [comment]
I want to reproduce the issue, so I need to know how did you compile `varnishlogbeat` and what version of go did you use.

**Comment by kfkawalec** [comment]
I do everything as is in Redme.
But, this problem is NOT for all request, I start service and everything is works fine.
But in some time there is special (?) request to varnish and this request generate error.
But I don't know how to simulate this request.

**Comment by phenomenes** [comment]
@kfkawalec I managed to reproduce the problem and pushed a fix over the weekend. Could you please checkout master and check if it fixes your problem?
